### ISSUE TITLE
Reporting error

### ISSUE THREAD

**Issue by debmercer144** [cstarcher/pysaf#1]
Hi,

Trying to use Pysaf and received this error. Thanks.

Deborah

ERROR:root:Error
Traceback (most recent call last):
  File "C:\Users\christopher\Desktop\v100\guiwin.py", line 336, in error_check
  File "C:\Users\christopher\Desktop\v100\guiwin.py", line 274, in main
  File "C:\Users\christopher\Desktop\v100\guiwin.py", line 267, in create_archive
  File "C:\Users\christopher\Desktop\v100\saf.py", line 219, in open_csv
  File "C:\Users\christopher\Desktop\v100\saf.py", line 206, in create_files
  File "C:\Users\christopher\Desktop\v100\saf.py", line 175, in write_schema_metadata
OSError: [Errno 22] Invalid argument: 'metadata_\ufefffilename\tdc.xml'

**Comment by cstarcher** [comment]
Deborah,

Would you mind sending me your CSV file?


On Feb 17, 2017, at 9:50 AM, debmercer144 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Trying to use Pysaf and received this error. Thanks.

Deborah

ERROR:root:Error
Traceback (most recent call last):
File "C:\Users\christopher\Desktop\v100\guiwin.py", line 336, in error_check
File "C:\Users\christopher\Desktop\v100\guiwin.py", line 274, in main
File "C:\Users\christopher\Desktop\v100\guiwin.py", line 267, in create_archive
File "C:\Users\christopher\Desktop\v100\saf.py", line 219, in open_csv
File "C:\Users\christopher\Desktop\v100\saf.py", line 206, in create_files
File "C:\Users\christopher\Desktop\v100\saf.py", line 175, in write_schema_metadata
OSError: [Errno 22] Invalid argument: 'metadata_\ufefffilename\tdc.xml'

**Comment by debmercer144** [comment]
Hi,

Sure. Here it is.

Deborah Mercer
New Jersey Collections Librarian
New Jersey State Library
185 West State Street
P.O. Box 520
Trenton, NJ 08625-0520
609.278.2640 x145
dmercer@njstatelib.org<mailto:dmercer@njstatelib.org>

Follow me on Twitter at  https://twitter.com/njdocslibrarian   [twitter]

**Comment by debmercer144** [comment]
Thanks for getting back to me but I also just reported the error because you requested it. I don’t expect you to solve my problems!

Deborah

Deborah Mercer
New Jersey Collections Librarian
New Jersey State Library
185 West State Street
P.O. Box 520
Trenton, NJ 08625-0520
609.278.2640 x145
dmercer@njstatelib.org<mailto:dmercer@njstatelib.org>

Follow me on Twitter at  https://twitter.com/njdocslibrarian   [twitter]
