### ISSUE TITLE
Received error message

### ISSUE THREAD

**Issue by JeannetteHo1** [cstarcher/pysaf#3]
I received the following error message.  Then I closed all applications on my computer and just ran PySAF, and still got the same error:

ERROR:root:Error
Traceback (most recent call last):
  File "C:\Users\christopher\Desktop\v100\guiwin.py", line 336, in error_check
  File "C:\Users\christopher\Desktop\v100\guiwin.py", line 274, in main
  File "C:\Users\christopher\Desktop\v100\guiwin.py", line 265, in create_archive
  File "C:\Users\christopher\Desktop\v100\saf.py", line 247, in open_csv_split
  File "C:\Users\christopher\AppData\Local\Programs\Python\Python35\lib\shutil.py", line 531, in move
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jaho\\Documents\\Fanzine 7\\2nd half\\SimpleArchiveFormat1\\item_32' -> 'C:/Users/jaho/Documents/Fanzine 7/2nd half\\SimpleArchiveFormat1\\item_32'

**Comment by cstarcher** [comment]
Thanks for reporting the error.

It looks like you may have selected the same directory for your archive destination (Select Archive Destination) as your original files (Select Location of Files) directory. Because PySAF traverses the entire directory tree of the original files folder, the archive destination directory must be outside of the original files directory.
